name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]
    tags:
    - '*'
  pull_request:
    branches: [ main ]
jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          ls
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with: 
          type: 'zip'
          filename: 'StorOne-ManagedApplication.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig R* c* m* StorOne-ManagedApplication/' 
          name: assets-for-download
          path: StorOne-ManagedApplication
          
      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          ls
          
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "StorOne-ManagedApplication.zip"
          tag: "zip2"
          replacesArtifacts: "true"
          allowUpdates: "true"
