name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]
    tags:
    - '*'
  pull_request:
    branches: '*'
jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Listing the contents
        run: |
          ls
          
      
      - name: Archive Release 2
        uses: papeloto/action-zip@v1
        with:
          files: StorOne-ManagedApplication/
          recursive: true
          dest: StorOne-ManagedApplication.zip
      
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "StorOne-ManagedApplication.zip"
          tag: "zip2"
          replacesArtifacts: "true"
          allowUpdates: "true"
          prerelease: "true"
          omitPrereleaseDuringUpdate: "true"
