name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: StorOne-ManagedApplication
          
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "assets-for-download.zip"
          tag: "zip1"
          replacesArtifacts: "true"
          allowUpdates: "true"
